#!/bin/bash

url = "https://pokeapi.co/api/v2/pokemon/pikachu"
response=$(curl -s -w "%{http_code}" -o data.json $url)

# Check if the response was successful
if [ $response -eq 200 ]; then
  echo "Request successful! Data saved to data.json"
else
  echo "Request failed with status code $response" >> errors.txt
  echo "Error! The response was: $response"
fi